[global]

[[global.environment]]
name = "ACTION_SECRET"
value = "{{ secrets.ACTION_SECRET }}"

[[global.environment]]
name = "HASURA_GRAPHQL_ADMIN_SECRET"
value = "{{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}"


[[global.environment]]
name = "LLM_PROVIDER"
value = "stub"


[hasura]
version = "v2.36.0"
adminSecret = "{{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}"
webhookSecret = "{{ secrets.NHOST_WEBHOOK_SECRET }}"

[auth]
version = "0.24.0"

[auth.method.emailPassword]
hibpEnabled = false

[auth.session.accessToken]
expiresIn = 900

[auth.session.refreshToken]
expiresIn = 43200

[postgres]
version = "14.6-20230605-1"

[functions]
[functions.node]
version = 20

[provider]